apiVersion: apps/v1
kind: deployment
metadata:
  name: pincode-service-deployment
  labels:
      name : pincode-service
spec:
  replicas : 2
  selectors:
    matchLabels :
      name:pincode-service
  template:
    metadata:
      labels:
        app: pincode-service
    spec:
      containers:
      - name: pincode
        image: pincode_image
        ports:
        - containerPort: 80
