apiVersion: apps/v1
kind: deployment
metadata:
  name: nginx-deployment
  labels:
      name : app
spec:
  replicas : 2
  selectors:
    matchLabels :
      app:nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
